"""empty message

Revision ID: c21759c6c924
Revises: a596299aaec8
Create Date: 2023-08-29 19:07:00.607145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21759c6c924'
down_revision = 'a596299aaec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=80), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('created', sa.String(length=120), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('edited', sa.String(length=120), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.Integer(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('passenger', sa.String(length=80), nullable=False),
    sa.Column('pilots', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created'),
    sa.UniqueConstraint('edited'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
